### ISSUE TITLE
libswiftnav-python inconsistent with libswiftnav

### ISSUE THREAD

**Issue by njoubert** [swift-nav/libswiftnav-python#7]
On building libswiftnav-python with current libswiftnav, I get:

swiftnav/dgnss_management.c:5099:539: error: too few arguments to function call, expected 6, have 5
  measure_b_with_external_ambs((&(___Pyx_BufPtrCContig1d(__pyx_t_5numpy_double_t *, __pyx_pybuffernd_ref_ecef_.rcbuffer->pybuffer.buf, __pyx_t_18, __pyx_pybuffernd_ref_ecef_.diminfo[0].strides))), __pyx_v_n, (&(__pyx_v_sdiffs[0])), (&(___Pyx_BufPtrCContig1d(__pyx_t_5numpy_double_t _, __pyx_pybuffernd_ambs_.rcbuffer->pybuffer.buf, __pyx_t_20, __pyx_pybuffernd_ambs_.diminfo[0].strides))), (&(___Pyx_BufPtrCContig1d(__pyx_t_5numpy_double_t *, __pyx_pybuffernd_b.rcbuffer->pybuffer.buf, __pyx_t_21, __pyx_pybuffernd_b.diminfo[0].strides))));

**Comment by imh** [comment]
i've had a PR in for ages trying to get someone to review it that addresses this. Wanna take a look neils? https://github.com/swift-nav/libswiftnav-python/pull/6

**Comment by njoubert** [comment]
Hey there sexy! Left you some comments! Sleep on that sweetie!


-Niels

**Comment by njoubert** [comment]
I'm cringing at my comments on this. I apologize profusely. Past Niels and
Past Ian had a special relationship that, in retrospect, reads quite
weirdly.



- Dr. Niels
