### ISSUE TITLE
Move almanac.py from sbp_log_analysis & piksi_tools to libswiftnav-python

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/libswiftnav-python#9]

**Comment by fnoble** [comment]
libswiftnav-python is really only supposed to have bindings to libswiftnav, it shouldn't have extra functionality not found in libswiftnav.

Luckily there is already a C implementation of the almanac code that could have bindings created.

**Comment by denniszollo** [comment]
I don't think our C implementation of libswiftnav should go making http requests / system calls to download almanac though.  Where should this utility live in the future?

**Comment by fnoble** [comment]
I dunno but probably not in libswiftnav, either piksi_tools or some other useful scripts repo as @mookerji was suggesting?
